//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Destino
    {
        public int IdDestino { get; set; }
        public string Pais { get; set; }
        public string Localidad { get; set; }
        public string Ciudad { get; set; }
        public int FechaDesde { get; set; }
        public int FechaHasta { get; set; }
        public int IdViaje { get; set; }
    }
}
