//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Viaje
    {
        public Viaje()
        {
            this.ViajeDestino = new HashSet<ViajeDestino>();
            this.ViajeVuelo = new HashSet<ViajeVuelo>();
        }
    
        public int IdViaje { get; set; }
        public string Alojamiento { get; set; }
        public int IdVuelo { get; set; }
        public int IdDestino { get; set; }
    
        public virtual ICollection<ViajeDestino> ViajeDestino { get; set; }
        public virtual ICollection<ViajeVuelo> ViajeVuelo { get; set; }
    }
}
