//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Genericas
{
    using System;
    using System.Collections.Generic;
    
    public partial class Destino
    {
        public Destino()
        {
            this.Viaje = new HashSet<Viaje>();
        }
    
        public int IdDestino { get; set; }
        public string Pais { get; set; }
        public string Localidad { get; set; }
        public string Ciudad { get; set; }
        public System.DateTime FechaDesde { get; set; }
        public System.DateTime FechaHasta { get; set; }
    
        public virtual ICollection<Viaje> Viaje { get; set; }
    }
}
