//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Genericas
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public Usuario()
        {
            this.Usuario1 = new HashSet<Usuario>();
            this.Usuario2 = new HashSet<Usuario>();
            this.Viaje = new HashSet<Viaje>();
        }
    
        public long IdUsuario { get; set; }
        public string NombreUsuario { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public Nullable<int> Edad { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public long IdRol { get; set; }
        public string MatriculaGuia { get; set; }
        public string Descripcion { get; set; }
        public long Nacionalidad { get; set; }
    
        public virtual Ciudad Ciudad { get; set; }
        public virtual ICollection<Usuario> Usuario1 { get; set; }
        public virtual ICollection<Usuario> Usuario2 { get; set; }
        public virtual ICollection<Viaje> Viaje { get; set; }
    }
}
