//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Genericas
{
    using System;
    using System.Collections.Generic;
    
    public partial class Viaje
    {
        public Viaje()
        {
            this.Usuario = new HashSet<Usuario>();
        }
    
        public long IdViaje { get; set; }
        public string Alojamiento { get; set; }
        public string Aerolinea { get; set; }
        public string NumeroVuelo { get; set; }
        public System.DateTime FechaDesde { get; set; }
        public Nullable<System.DateTime> FechaHasta { get; set; }
        public Nullable<long> IdUsuario { get; set; }
        public long IdOrigen { get; set; }
        public long IdDestino { get; set; }
        public Nullable<bool> InteresActividades { get; set; }
        public Nullable<bool> InteresExcursiones { get; set; }
        public Nullable<bool> InteresTraslados { get; set; }
        public Nullable<bool> InteresAmistades { get; set; }
        public Nullable<bool> InteresAlojamiento { get; set; }
        public Nullable<bool> InteresOtros { get; set; }
    
        public virtual Ciudad Ciudad { get; set; }
        public virtual Ciudad Ciudad1 { get; set; }
        public virtual ICollection<Usuario> Usuario { get; set; }
    }
}
