//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Genericas
{
    using System;
    using System.Collections.Generic;
    
    public partial class Viaje
    {
        public Viaje()
        {
            this.Destino = new HashSet<Destino>();
            this.Vuelo = new HashSet<Vuelo>();
        }
    
        public int IdViaje { get; set; }
        public string Alojamiento { get; set; }
        public int IdUsuario { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        public virtual ICollection<Destino> Destino { get; set; }
        public virtual ICollection<Vuelo> Vuelo { get; set; }
    }
}
