//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Genericas
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vuelo
    {
        public Vuelo()
        {
            this.Viaje = new HashSet<Viaje>();
        }
    
        public int IdVuelo { get; set; }
        public string Aerolinea { get; set; }
        public int NumeroVuelo { get; set; }
        public System.DateTime FechaVuelo { get; set; }
    
        public virtual ICollection<Viaje> Viaje { get; set; }
    }
}
